name: Prison
main: org.runaway.Prison
version: 2.1
author: _RunAway_
api-version: 1.18
softdepend:
- HolographicDisplays
- PermissionsEx
- NametagEdit
- ViaVersion
- Citizens
- ArmorEquipEvent
- FastAsyncWorldEdit
- BetterHud
- ItemsAdder
- PlaceholderAPI